version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Ba17ri
      MYSQL_DATABASE: trade_database
      MYSQL_USER: conquer
      MYSQL_PASSWORD: Ba17ri
    ports:
      - "3306:3306"
